{% set name = "sdl" %}
{% set version = "1.2.52" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/libsdl-org/sdl12-compat/archive/refs/tags/release-{{ version }}.tar.gz
    sha256: d6d316a793e5e348155f0dd93b979798933fb98aa1edebcc108829d6474aad00


build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja

  host:
    - sdl2

test:
  commands:
    - test -f ${PREFIX}/include/SDL/SDL.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\SDL\\SDL.h exit 1  # [win]

about:
  home: https://www.libsdl.org/index.php
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Simple DirectMedia Layer

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
