{% set name = "sdl3" %}
{% set version = "3.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/SDL/releases/download/release-{{ version }}/SDL3-{{ version }}.tar.gz
  sha256: f87be7b4dec66db4098e9c167b2aa34e2ca10aeb5443bdde95ae03185ed513e0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make                # [not win]
    - ninja               # [win]
    - pkg-config
  host:
    - libusb
    - libvulkan-loader
    - dbus                # [not win]
    - jack                # [linux]
    - pulseaudio          # [linux]
    - wayland             # [linux]
    - libdrm              # [linux]
    - libudev             # [linux]
    - liburing            # [linux]
    - libunwind           # [linux]
    - libxkbcommon        # [linux]
    - libgl-devel         # [linux]
    - libegl-devel        # [linux]
    - xorg-libx11         # [linux]
    - xorg-libxext        # [linux]
    - xorg-libxfixes      # [linux]
    - xorg-libxcursor     # [linux]
    - xorg-libxscrnsaver  # [linux and x86_64]
  run:
    - xorg-libx11         # [linux]
    - xorg-libxext        # [linux]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f ${PREFIX}/include/SDL3/SDL.h  # [not win]

about:
  home: https://www.libsdl.org/
  summary: Low-level access to audio, keyboard, mouse, joystick, and graphics
  description: |
    Simple DirectMedia Layer (SDL for short) is a cross-platform library designed
    to make it easy to write multi-media software, such as games and emulators.
  license: Zlib
  license_file: LICENSE.txt
  doc_url: https://wiki.libsdl.org/SDL3/FrontPage
  dev_url: https://github.com/libsdl-org/SDL

extra:
  recipe-maintainers:
    - traversaro
    - ymontmarin
    - ManifoldFR
