{% set name = "sdl2" %}
{% set version = "2.32.54" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/sdl2-compat/releases/download/release-{{ version }}/sdl2-compat-{{ version }}.tar.gz
  sha256: c680c004db48604348ec8a1527b998aa653b8103f2589e5a52e26d5e35f1de66

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
    - pkg-config
  host:
    - sdl3
    - libgl-devel   # [linux]
    - libegl-devel  # [linux]

test:
  requires:
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  files:
    - cmake_test/
    - test_version.sh
    - test_version.bat
  commands:
    - sdl2-config --version  # [not win]
    - ./test_version.sh      # [unix]
    - ./test_version.bat     # [win]
    - pkg-config --exists sdl2

about:
  home: https://www.libsdl.org/index.php
  license: Zlib
  license_file: LICENSE.txt
  summary: Low-level access to audio, keyboard, mouse, joystick, and graphics
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://wiki.libsdl.org/FrontPage
  dev_url: http://hg.libsdl.org/SDL

extra:
  recipe-maintainers:
    - ymontmarin
    - dschreij
    - matham
