{% set name = "sdl3" %}
{% set version = "3.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/SDL/releases/download/release-{{ version }}/SDL3-{{ version }}.tar.gz
  sha256: 2938328317301dfbe30176d79c251733aa5e7ec5c436c800b99ed4da7adcb0f0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - sdl2
    - libglu              # [linux]
    - libgl-devel         # [linux]
    - libopengl           # [linux]
    - xorg-libx11         # [linux]
    - xorg-libxext        # [linux]
  run:
    - sdl2

test:
  commands:
    - test -f ${PREFIX}/include/SDL/SDL.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\SDL\\SDL.h exit 1  # [win]
    - pkg-config --exists --print-errors --debug sdl  # [not win]
    - pkg-config --validate --print-errors --debug sdl  # [not win]
  requires:
    - pkg-config

about:
  home: https://www.libsdl.org/index.php
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Simple DirectMedia Layer

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
    - ymontmarin
