{% set name = "sdl" %}
{% set version = "1.2.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://www.libsdl.org/release/SDL-{{ version }}.tar.gz
    sha256: d6d316a793e5e348155f0dd93b979798933fb98aa1edebcc108829d6474aad00
    patches:
      - osx_patches.patch  # [osx]
  - path: CMakeLists.txt

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - gnuconfig              # [unix]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('c') }}    # [not win]
    - cmake                  # [win]
    - ninja                  # [win]
    - make                   # [unix]

  host:
    - xorg-libx11   # [osx]
    - xorg-libxext  # [osx]

  run:
    - xorg-libx11   # [osx]
    - xorg-libxext  # [osx]

test:
  commands:
    - test -f ${PREFIX}/include/SDL/SDL.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\SDL\\SDL.h exit 1  # [win]

about:
  home: https://www.libsdl.org/index.php
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: |
    Simple DirectMedia Layer

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
    - Tobias-Fischer
