schema_version: 1

context:
  name: sdl3
  version: 3.2.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/libsdl-org/SDL/releases/download/release-${{ version }}/SDL3-${{ version }}.tar.gz
  sha256: f87be7b4dec66db4098e9c167b2aa34e2ca10aeb5443bdde95ae03185ed513e0

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: not win
      then: make
    - if: win
      then: ninja
    - pkg-config
  host:
    - libusb
    - libvulkan-loader
    - if: not win
      then: dbus
    - if: linux
      then: jack
    - if: linux
      then: pulseaudio
    - if: linux
      then: wayland
    - if: linux
      then: libdrm
    - if: linux
      then: libudev
    - if: linux
      then: liburing
    - if: linux
      then: libunwind
    - if: linux
      then: libxkbcommon
    - if: linux
      then: libgl-devel
    - if: linux
      then: libegl-devel
    - if: linux
      then: xorg-libx11
    - if: linux
      then: xorg-libxext
    - if: linux
      then: xorg-libxfixes
    - if: linux
      then: xorg-libxcursor
    - if: linux and x86_64
      then: xorg-libxscrnsaver
  run:
    - if: linux
      then: xorg-libx11
    - if: linux
      then: xorg-libxext
  run_exports:
    - ${{ pin_subpackage(name|lower, upper_bound='x') }}

tests:
  - requirements:
      run:
        - pkg-config
    script:
      - pkg-config --modversion ${{ name }}
      - if: not win
        then: test -f ${PREFIX}/include/SDL3/SDL.h

about:
  summary: Low-level access to audio, keyboard, mouse, joystick, and graphics
  description: |
    Simple DirectMedia Layer (SDL for short) is a cross-platform library designed
    to make it easy to write multi-media software, such as games and emulators.
  license: Zlib
  license_file: LICENSE.txt
  homepage: https://www.libsdl.org/
  repository: https://github.com/libsdl-org/SDL
  documentation: https://wiki.libsdl.org/SDL3/FrontPage

extra:
  recipe-maintainers:
    - traversaro
    - ymontmarin
    - ManifoldFR
